// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0SXFlyPPglbRvmqLAgrGK6G3iltmI00',
    appId: '1:488319503658:web:c019f66abe33c0520de253',
    messagingSenderId: '488319503658',
    projectId: 'to-do-app-bfe40',
    authDomain: 'to-do-app-bfe40.firebaseapp.com',
    storageBucket: 'to-do-app-bfe40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJOfpqkYCqS_biE5MPS-EtmeDKNCUHQ3c',
    appId: '1:488319503658:android:a3111c5d5c1be4c00de253',
    messagingSenderId: '488319503658',
    projectId: 'to-do-app-bfe40',
    storageBucket: 'to-do-app-bfe40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFNMi63YO9n9xfT27jsQB_BwRNbIAHdwc',
    appId: '1:488319503658:ios:ff5574b71a1834e00de253',
    messagingSenderId: '488319503658',
    projectId: 'to-do-app-bfe40',
    storageBucket: 'to-do-app-bfe40.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
